name: Update Quote

on:
  workflow_dispatch: # Manually trigger the workflow
  schedule:
    - cron: '30 6 * * *' # Runs daily at 6:30 UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 14

      - name: Install dependencies (without generating package-lock.json)
        run: npm install --no-package-lock

      - name: Update Quote
        run: node update-quote.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config user.name 'khalidkarimkqr'
          git config user.email 'khalid13878@hotmail.com'
          git add README.md
          git commit -m "Update README with daily quote" || echo "No changes to commit"
          git push
